### ISSUE TITLE
Integrate codecov.io

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#137]
In order to ensure our code has been fully tested, integrate code coverage testing in our continuous integration.

**Comment by rfdickerson** [comment]
I think this would be amazing to implement. However, codecov (for Swift projects) requires xcodebuild command line tool to build and launch XCTests. This is of course, because codecov ensures that most of the lines of code is executed in the test suite.

It doesn't seem clear to me that 'swift build' in SPM and opensource XCTests can integrate with this tool.

**Comment by rfdickerson** [comment]
I opened an issue regarding this enhancement: 
https://github.com/codecov/support/issues/142

**Comment by rfdickerson** [comment]
I'm making progress here. We almost have codecov integrated into HeliumLogger. 
https://travis-ci.org/IBM-Swift/HeliumLogger/builds/124042454

**Comment by rfdickerson** [comment]
```

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                e2e0ba7
(url) https://codecov.io
(root) .
==> Travis CI detected.
  -> Swift in /Users/travis/Library/Developer/Xcode/DerivedData
  -> Speed up xcode processing by using use -J 'AppName'
    + Building reports for Package xctest
error: Failed to load coverage: No such file or directory
==> Running gcov (disable via -X gcov)
  -> Obj-C in /Users/travis/Library/Developer/Xcode/DerivedData
  -> gcov in .
==> Searching for coverage reports
**> Python coverage not found
==> Detecting git/mercurial file structure
==> Reading reports
  + ./Package.xctest.coverage.txt bytes=0
==> Appending adjustments (http://bit.ly/1O4eBpt)
  --> Found 23 adjustments
(query) branch=master&commit=017970e38d90efc563c8aed5fcbf7aaac5f2db56&build=23.1&build_url=&slug=IBM-Swift/HeliumLogger&service=travis-org&pr=false&job=124048258
==> Uploading reports
    Pinging Codecov
    Uploading to S3
Reports queued to http://codecov.io/github/IBM-Swift/HeliumLogger?ref=017970e38d90efc563c8aed5fcbf7aaac5f2db56

```

**Comment by rfdickerson** [comment]
I tried the following, and although it worked for someone, it hasn't fixed the problem:

https://github.com/codecov/example-swift/issues/5

**Comment by rfdickerson** [comment]
Update:

I can get profiling information generated on running the test cases running:

```
swift build -Xswiftc -profile-generate -Xswiftc -profile-coverage-mapping
```

run the tests as normal with `swift test`

Now, since the default version of LLVM does not work on Swift toolchains, you have to use the modified version of LLVM in the Swift repositories.

```
/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/llvm-profdata merge -o testprof.profdata default.profraw
```

generates the data. However, the last step I'm stuck. Apparently you can run `llvm-cov` to generate code coverage logs. But it fails.

**Comment by rfdickerson** [comment]
Update: 4/25 toolchain does not fix this issue.

**Comment by na-gupta** [comment]
This has been integrated into Package-Builder/build-package.sh (https://github.com/IBM-Swift/Package-Builder/blob/master/codecov.sh) and code coverage gets generated automatically for any repos that utilize Package-Builder/build-package.sh and setup a cron build in travis.
