### ISSUE TITLE
Ability to limit incoming request size

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1384]
## Context and Description
Kitura currently does not have the concept of a limit on incoming request size.  It is possible to destabilize a server by sending (accidentally or maliciously) a large request payload which either impairs performance, or exhausts available memory.

A limit should be configurable on a server which causes requests above that size to be rejected, and the connection closed.

**Comment by djones6** [comment]
Prototype for discussion here: https://github.com/IBM-Swift/Kitura/commit/707bf6d9a00a6d80f0d91c09de384700fbe1e7fb
This requires the corresponding changes to Kitura-net in this branch: https://github.com/IBM-Swift/Kitura-net/tree/requestLimit

In this prototype I implemented both the `requestSizeLimit` (maximum bytes for a request, _including_ the headers) and `connectionLimit` on total number of concurrent connections.

Example usage is as follows:
```swift
let connectionPolicy = IncomingSocketOptions(requestSizeLimit: 100, connectionLimit: 3)
Kitura.addHTTPServer(onPort: port, with: router, connectionPolicy: connectionPolicy)
```

Some issues I'm aware of:
- There are already parameters `keepAlive` and `allowPortReuse` on `Kitura.addHTTPServer` which could be rolled into this new options struct.
- The policing of the read limit is inexact: we read as many bytes as are provided to us in the next read operation, and if that causes us to exceed the read buffer limit, we then fail.
- I didn't reject immediately in the case where the client provided a `Content-Length` (yet). This would save cycles in the case where a client is well-behaved.

**Comment by moshegottlieb** [comment]
@djones6 I would like to see some additional flexibility.  
In particular - I would like to install handlers for the error messages so that the response can customized (a human readable error message specifying the actual limit, for instance) and the request can be logged.  
It would have been nice to add additional custom handlers and allow the app to override the defaults (for instance, allow `POST /video` a max size that is bigger than `POST /image`) but this can be added in future versions and probably requires a design of it’s own.  
As for connection limits - I think the default should be way lower.  
I’m writing this from my iPad and can’t check and to be honest I don’t know exactly what is the threading model for incoming connection, but if it’s a standard asynchronous dispatch queue, a simple semaphore can be used to limit the connection number while retaining backward support.  
Regardless - I think the connection limit should be way smaller, the default “max files” in my Ubuntu is 1024, the default number should be significantly lower than this.

**Comment by djones6** [comment]
I've updated this prototype to provide the ability to customize the response to the client: https://github.com/IBM-Swift/Kitura/compare/fb5dbc2...requestLimit

The handler is provided the current limit (that was exceeded) and the remote address of the client.

Logging details of the request is not so easy: as the point of this is to avoid reading beyond a certain limit, then we cannot consume and parse the request in order to inspect it (we cannot be sure that we can even read the request headers fully, as it would be possible to defeat this by sending a large or malformed header).

It would be possible to provide access to the current read buffer to the handler, the contents of which could then be logged.  But doing so exposes internals of Kitura-net, and to avoid this involves creating another copy of the data (which also defeats the purpose). 

A potential compromise would be to provide just the first n bytes of the read buffer to the handler, which might be sufficient to capture details such as the HTTP method, path and parameters.

**Comment by djones6** [comment]
@pushkarnk will raise issue for prototyping equivalent for NIO
