### ISSUE TITLE
If application ends with error, the process exit code should be different than 0

### ISSUE THREAD

**Issue by krzyzanowskim** [IBM-Swift/Kitura#1418]
The "Hello World" Kitura application error handling is not optimal. For the case presented below, the executable exit with exit code 0 - that means "success", while there was an error and exit code should be different than 0 (eg. 1).

If application ends with error, the process exit code should be different than 0

```
$ ./Hello
[2019-03-12T09:14:35.698+01:00] [WARNING] [ConfigurationManager.swift:389 load(url:deserializerName:)] Unable to load data from URL /Users/marcinkrzyzanowski/Devel/SwiftStudio/Examples/Kitura/Hello/.build/x86_64-apple-macosx/debug/config/mappings.json
[Tue Mar 12 09:14:35 2019] com.ibm.diagnostics.healthcenter.loader INFO: Swift Application Metrics
[2019-03-12T09:14:35.744+01:00] [INFO] [Metrics.swift:20 initializeMetrics(router:)] Initialized metrics.
[2019-03-12T09:14:35.746+01:00] [INFO] [Application.swift:28 run()] http://localhost:8080/
[2019-03-12T09:14:35.748+01:00] [ERROR] [Kitura.swift:139 start()] Error listening on port 8080: Error code: -9992(0x-2708), Address already in use. Use server.failed(callback:) to handle
$ echo $?
0
```

**Comment by sympatheticmoose** [comment]
related issue - https://github.com/IBM-Swift/Kitura/issues/1191

**Comment by ianpartridge** [comment]
Thanks Marcin, we will take a look ASAP.

**Comment by djones6** [comment]
I agree, this behaviour is unusual.  There are several possible ways we could behave, due to how Kitura starts listeners (there can be more than one), and what `Kitura.run()` does.

For a simple application that contains a single listener socket (typically 8080 or 8090), this is usually followed by invoking `Kitura.run()` on the main thread.

`Kitura.run()` will first invoke `Kitura.start()`, which:
    - tries to create a socket on the specified port, and listen for incoming connections
    - if successful, a background thread is created to accept new connections to the socket.

`Kitura.run()` will then block, waiting for all listeners to complete (indefinitely, or until `Kitura.stop()` is called).

In the case where the port is unavailable, that listener will fail to start.  We currently log an error here, but do not produce any return code, nor do we call `exit()`.

The reason for this is that you may have registered multiple listeners, some that succeed and some that do not.  The current behaviour is that Kitura will function on whichever listeners succeeded, unless they _all_ failed, in which case `run()` returns immediately.  Your application's main thread then continues, typically reaching the end of your `main.swift` and exiting with a zero status.

Ways that we could fix this:
- we could keep a count of the number of listeners that fail, and return this from `Kitura.start()` and `Kitura.run()` (although the latter will not return if at least one listener succeeded).  These would need to be new functions, as changing the `Void` return type would be a breaking change.
- we could choose for this additional variant of `Kitura.run()` to return immediately if any listeners failed.
- we could provide an additional variant of `Kitura.run()` that causes the process to exit if any listeners failed.
Eg:
```swift
public class Kitura {
    ...
    public class func startWithStatus() -> Int {
        // as per start(), but return number of listeners that failed
    }

    public class func runWithStatus() -> Int {
        let numFailures = startWithStatus()
        if numFailures == 0 {
            ListenerGroup.waitForListeners()
        }
        return numFailures
    }

    public class func runOrExit() {
        let numFailures = startWithStatus()
        if numFailures > 0 {
            exit(Int32(numFailures))
        }
        ListenerGroup.waitForListeners()
    }
}
```
To use this in your application, you'd replace your exiting `Kitura.run()` with either:
```swift
let status = Kitura.run()
exit(Int32(status))
```
or just
```swift
Kitura.runOrExit()
```

**Comment by djones6** [comment]
An alternative, throw an error if any listener fails to start:
```swift
    public class func runOrFail() throws {
        Log.verbose("Starting Kitura framework...")
        let numFailures = startWithStatus()
        if numFailures > 0 {
            throw Error.failedToStartListeners(numFailures: numFailures)
        }
        ListenerGroup.waitForListeners()
    }
```
(though it might be more helpful to know which listeners failed)

**Comment by djones6** [comment]
@krzyzanowskim #1430 has been merged to master and will be tagged in the next minor of Kitura (2.8) since it adds new public API.  Let me know if you require an interrim solution as we could potentially back-port a subset of these changes to Kitura 2.7.

**Comment by krzyzanowskim** [comment]
thank you! I don't need backport, thanks for asking.

**Comment by djones6** [comment]
This is now tagged in Kitura `2.8.0`.
