### ISSUE TITLE
Complete the easy to use Swift based Redis API

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#22]
<a href="https://github.ibm.com/KALLNER"><img src="https://avatars.github.ibm.com/u/3096?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KALLNER](https://github.ibm.com/KALLNER)**
_Friday Jan 08, 2016 at 11:57 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/22_

---

Add easy to use APIs for Redis List, Set, Sorted set, Transactional List, Transactional Set, and Transactional Sorted set  operations.

**Comment by kfbishop** [comment]
Is there any value in maintaining our own Redis driver, with respect to RedBird?  If we do not offer any specific competitive advantage or revenue potential, then we shouldn't roll our own.  Let's utilize the effort of others.

**Comment by rfdickerson** [comment]
Currently working on this: Can create, read, update, delete items in Redis- but still some issues getting all the test cases passing:

https://github.com/IBM-Swift/kitura-todolist-redis/

**Comment by shmuelk** [comment]
The advantage of Kitura-redis of RedBird is type safety and the ability to send binary data. Rather than simply passing in strings, Kitura-redis has a set of functions for most of the Redis API. These functions all take the appropriate types and have callbacks with appropriate types.

There once was an advantage to RedBird over Kitura-redis, in that RedBird is pure Swift and Kitura-redis wasn't.

This is no longer the case. Kitura-redis is now pure Swift as well. The old CHiredis dependency is no longer used (as of yesterday in the develop branch)

**Comment by christiancompton** [comment]
Closing - Reopen as needed.
