### ISSUE TITLE
Add functionality to specify param specific middleware

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#295]
Example from Express:
router.param('user', function(req, res, next, id) {
  console.Log(':user is present in route path');
  next();
});

**Comment by naithar** [comment]
I have started implementing this feature and it seems to be working without any problems on Mac, but Linux tests are failing at this moment.
https://github.com/naithar/Kitura/blob/develop/Sources/Kitura/Router.swift#L610-622
https://github.com/naithar/Kitura/blob/develop/Sources/Kitura/RouterParameter.swift
https://github.com/naithar/Kitura/blob/develop/Sources/Kitura/RouterMiddlewareWalker.swift

**Comment by shmuelk** [comment]
We will review and hopefully merge the above PR early next week in our next sprint

**Comment by naithar** [comment]
@shmuelk I tried to reimplement ```parameter``` method again with express.js in mind, but currently I'm not sure it is alright to make a PR. 
The problem is actually that I'm not sure that parameter handlers should be stored in separate list and be passed down to element looper and element's ```process``` method as i currently did. If there is no problem with such implementation, I'll clean the code and make a PR for review.
https://github.com/naithar/Kitura/blob/develop/Sources/Kitura/Router.swift#L717-721
https://github.com/naithar/Kitura/blob/develop/Sources/Kitura/RouterElementWalker.swift#L55-58
https://github.com/naithar/Kitura/blob/develop/Sources/Kitura/RouterElement.swift#L134-139
