### ISSUE TITLE
Specify argument to 'next' to skip to next route

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#298]
Equivalent to `next('route')` in Express

**Comment by tunniclm** [comment]
I had a go at implementing this functionality in a couple of ways, here are the compare links:
https://github.com/IBM-Swift/Kitura/compare/develop...tunniclm:add_next_route_using_object
https://github.com/IBM-Swift/Kitura/compare/develop...tunniclm:add_next_route_using_variadics

Unfortunately swift closures can't have default arguments, which would probably be the preferred way to implement this. Even using a function with default arguments isn't a workaround, because it needs to be passed as a parameter, at which point it loses the default argument information.

**Comment by christiancompton** [comment]
Closing - reopen as needed.
