### ISSUE TITLE
Verbose class names

### ISSUE THREAD

**Issue by casamm** [IBM-Swift/Kitura#323]
I feel like class prefixes (a convention from objective-c) are still followed in this implementation while in Swift [name-spacing is implicit scoped by module](https://twitter.com/clattner_llvm/status/474730716941385729).

Since class prefixes aren't needed, wouldn't be nice if class names are as follows. Non-verbose, elegant and simple.

- Element.swift
- Middleware.swift
- MiddlewareGenerator.swift
- Request.swift
- Response.swift

**Comment by rfdickerson** [comment]
Agreed. We hope to simplify some of the class names in the future. In addition, use a more protocol-oriented programming style as we eventually refactor this work.

**Comment by sshams** [comment]
@rfdickerson that's even better, _"program to an interface, not an implementation"_

Naming convention for protocols in Objective-C has been different but it's Swift, I've preceded letter "I" before protocol names (a convention from Java, C# etc.) in several of my swift repos since Swift closely resembles these language styles and conventions.

I'd recommend naming protocols as `IRequest`, `IResponse` to match corresponding pairs of `Request` and `Response` and using them as types for parameters on method signatures. Same for other actors in your system.

**Comment by rfdickerson** [comment]
I agree with "program to an interface, not an implementation". Protocol-oriented programming always says "start with the protocol". However, I worry that the "I" prefix seems to be out of favor in the Swift community, at least for the Apple libraries. But I am aware of it from the days when I was a Java and C++ programmer. We are investigating matching more of the data structures and protocols proposed in the S4 standard. 

https://github.com/SwiftX/S4

**Comment by sshams** [comment]
I liked the SwifX/S4 standard, short and concise, would love to see it getting reflected in Kitura.

**Comment by dfirsht** [comment]
I'm going to close this issue, if you have suggestions for things that we can change, you can add them as a comment to issue #348.

**Comment by casamm** [comment]
Not seeing any S4 standards, class names are still verbose.
