### ISSUE TITLE
Kitura does not use all available CPU

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#409]
When driven with constant load, Kitura (on Linux) does not make use of all the CPU available to it.  Utilization also does not increase linearly as more hardware threads are added.
Some examples from a simple 'hello world' response with requests driven using 'wrk' for 10 seconds:
1 core:    `6675 resp/s,   70ms avg,  cpu = 9.5sec,    93.8%`
2 cores:  `10447 resp/s,  21ms avg,  cpu = 14.3sec,  73.4% / 68.7%`
3 cores:  `16113 resp/s,  30ms avg,  cpu = 23.8sec,  74.1% / 80.7% / 82.8%`
4 cores:  `21197 resp/s,  23ms avg,  cpu = 33.2sec,  86.7% / 76.9% / 84.0% / 84.8%`
6 cores:  `29559 resp/s,  31ms avg,  cpu = 45.3sec,  64.6% / 70.9% / 82.1% / 76.4% / 82.0% / 81.8%`
8 cores:  `36261 resp/s,  28ms avg,  cpu = 58.5sec,  61.5% / 50.0% / 54.0% / 89.9% / 89.6% / 89.0% / 80.5% / 69.0%`
8 + HT:   `41126 resp/s,  19ms avg,  cpu = 83.2sec,  69.9% / 58.0% / 45.6% / 48.8% / 45.1% / 35.4% / 48.8% / 63.2% / 32.9% / 34.5% / 74.7% / 71.8% / 37.9% / 74.1% / 36.1% / 37.8%`

Load driver command:
`numactl --cpunodebind=1 --membind=1 /home/djones6/kiturabench/wrk -t16 -c128 -d10s http://127.0.0.1:8080/plaintext`
Kitura command (example from 4 cores above):
`numactl --physcpubind=0,1,2,3 --membind=0 /home/djones6/git-projects/bbmark/swift/kitura/.build/release/kitura`
(sample code is here: https://github.com/antonmes/bbmark/blob/master/swift/kitura/Sources/main.swift)

System / load driver has plenty of headroom - eg. here are equivalent numbers driving Zewo with 16 instances (pinned to the same 8 cores + hyperthreading):
8 + HT:   `169430 resp/s,  4.9ms avg,  cpu = 159.8sec  99.9% / 99.8% / 99.9% / 100.0% / 100.0% / 99.9% / 99.9% / 99.8% / 99.9% / 99.9% / 99.9% / 99.9% / 99.9% / 99.9% / 99.9% / 99.9%`

Things to investigate:
- Does KItura scale on OS X?  (ie. could it be Linux Dispatch related?)
- If not, can we pinpoint some contention / blocking?

**Comment by djones6** [comment]
I'm currently working on this. Update:

Getting Kitura to run with any consistency on Mac is infeasible without Keepalive support (as the rapid creation / closure of connections on Mac seems to have a high overhead and the OS periodically gets busy doing something else - possibly logging, or some diagnostics component trying to figure out just what is going on).
Zewo can run consistently - albeit I could only get a single instance running, ie. single-threaded - so I suspect that once Keepalive is working, I can revisit this comparison.

I've observed that simple testcases / benchmarks that use Dispatch will scale to use all available CPU - in other words, Dispatch itself is not preventing us scaling.  My conclusion at this point is that there's something specifically Kitura related which is not scaling.  I need to debug why the Kitura code _isn't_ running.

The tool I want to use to do this ([perf: profiling sleep times](https://perf.wiki.kernel.org/index.php/Tutorial#Profiling_sleep_times)) requires Linux scheduler tracepoints.  A combination of a misleading error message, lapse of brain, and finding answers to a problem I didn't have, led me to figure out how to rebuild the Ubuntu kernel:
```
perf record -e sched:sched_stat_sleep -e sched:sched_switch  -e sched:sched_process_exit -g -o perf.data.raw ./build_pr32/release/TechEmpower
event syntax error: 'sched:sched_stat_sleep'
                     \___ unknown tracepoint
```
... perf needs root permissions to 'see' these tracepoints, but I forgot to sudo.  Searching for 'perf sched_stat_sleep unknown tracepoint', I found this:
http://stackoverflow.com/questions/21756067/profiling-sleep-times-with-perf
This, and other search results, pointed me to CONFIG_SCHEDSTATS and that I would need to rebuild the kernel.  After figuring out how to do so, and finding it still didn't work, I realised my mistake.  Turns out, the original kernel had the tracepoints after all.

If I profile for more than a few seconds, I get another problem reported by perf record (and later, perf inject):
`0x855bb8 [0xd0]: failed to process type: 9`
Initially I thought my profiling was still broken, but taking a short sample, I get some output:
```
root@needletail:~/Kitura-TechEmpower_015# perf record -e sched:sched_stat_sleep -e sched:sched_switch  -e sched:sched_process_exit -e sched:sched_stat_wait -e sched:sched_stat_iowait -e sched:sched_stat_blocked -e sched:sched_wait_task -g -o perf.data.raw numactl --physcpubind=0-3 --membind=0 .build/debug/TechEmpower
(...drive load, ^C after 5 seconds)
[ perf record: Woken up 8 times to write data ]
Warning: Processed 56847 events and lost 2 chunks!
Check IO/CPU overload!
Warning: 11333 out of order events recorded.
[ perf record: Captured and wrote 10.913 MB perf.data.raw (56215 samples) ]

root@needletail:~/Kitura-TechEmpower_015# perf inject -v -s -i perf.data.raw -o perf.data
...
overriding event (273) sched:sched_switch with new print handler
build id event received for /usr/lib/debug/boot/vmlinux-4.2.0-36-generic: 36dc20f171e4ac6c5643ddc4e09960b5dffd5ed5
Using /root/.debug/.build-id/36/dc20f171e4ac6c5643ddc4e09960b5dffd5ed5 for symbols
root@needletail:~/Kitura-TechEmpower_015# perf report > perf-report.out
Failed to open /tmp/perf-3978.map, continuing without symbols
Warning:
Processed 54614 events and lost 2 chunks!
Check IO/CPU overload!

root@needletail:~/Kitura-TechEmpower_015# cat perf-report.out | swift-demangle > perf-report.demangled.txt
```
Here's the output - next step is to figure out what (if anything) this is telling me...
[perf-report.demangled.txt](https://github.com/IBM-Swift/Kitura/files/300814/perf-report.demangled.txt)

**Comment by djones6** [comment]
Now that keepalive has been prototyped (#435), I can see the same idle time on Mac.
Kitura, the kernel and the load driver combined use ~93% of the available CPU on my MacBook Pro (4 cores + hyperthreading), ie. ~7% idle time.
An equivalent run using Vapor fully utilizes the system (~100%).

**Comment by ymanton** [comment]
With @djones6's help I've recreated his pre-keepalive numbers on a setup here and indeed there is plenty of CPU left on the table when running with more than one CPU.

![image](https://cloud.githubusercontent.com/assets/926840/17144950/89f51d48-5326-11e6-9012-c51e3e23e1db.png)

I'm interested to know how many threads Kitura is running on the back end to service these clients. From what I saw in perf when running with 8 clients there were 20 threads running Swift code, although the distribution of ticks was very uneven, and it wasn't immediately obvious to me which threads were servicing clients and which were doing other things or what those other things were.

What I would expect to see here is a high number of blocked client-servicing threads throughout the run, because if they aren't blocked and are instead runnable they should be running (plenty of CPU resources are available), and if they were running and doing work (or spinning) they should be contributing to the CPU utilization. If there are indeed blocked threads we should be able to determine what they're blocked on.

**Comment by ymanton** [comment]
I noticed that my throughput numbers did not compare to yours @djones6, and I had some file IO activity that I wasn't expecting from a "hello world" application. Turns out the URL I pointed the driver at was the root, which actually serves up a default Kitura page with text and graphics. Switching to /plaintext fixed that, although the CPU utilization isn't too different...

![image](https://cloud.githubusercontent.com/assets/926840/17196956/58759f66-5436-11e6-83af-76d220d908ed.png)

Anyhow, as far as blocked threads go, `perf record -e sched:sched_switch` is actually the most useful tracepoint to profile, it's the one that is triggered when a CPU switches from thread to thread (or to/from idle) and it tells you why the switch is happening. If you grab a callstack profile with that tracepoint and only consider samples where a thread yielded the CPU due to being blocked the one thing that's noticeable is that memory allocation (via `malloc`) is prominent. Normally `malloc` shouldn't block, modern Glibc uses multiple "sub-heaps" to avoid threads contending on a single one, so I'm not sure why we're seeing so many `malloc` calls ending up in a blocking operation, but that looks like an interesting avenue to pursue...

Side note: for x86-64 `--call-stack dwarf` is usually required to get accurate callstacks, as opposed to `-g` (which is short for `--call-stack fp` and is only reliable for x86-32).

**Comment by ianpartridge** [comment]
On Linux, if a `malloc` is above a certain size, the kernel diverts the request to `mmap` in a slowpath. Doing that involves taking a lock, so this could be the cause?

**Comment by ymanton** [comment]
@ianpartridge, yeah that occurred to me as well. The size at which `malloc` starts to defer to `mmap` under the covers is at least 128KiB, and Kitura allocating that much memory for a simple "hello world" response would itself be dubious, but `mmap` does not appear on the callstack. I tried bumping the threshold up to 16MiB, but that didn't change anything unfortunately.

The easiest experiment I can think of is to simply get rid of those `malloc` calls and see if that changes anything, so I'll give that a try just as soon as I figure out how I can get the equivalent of a stack allocation in Swift.

**Comment by ianpartridge** [comment]
@djones6 has been using `massif` from valgrind to get allocation stacks.

**Comment by ymanton** [comment]
So I tried hacking around a couple of `malloc` calls, but that did not change CPU utilization or performance; the bottleneck just seemed to migrate elsewhere. I did find another potential performance issue that should be revisited, but as far as this issue goes it was a dead end.

Turns out that Dispatch (more specifically `libpwq`) needs to know how many logical CPUs are available to the process in order to effectively manage its thread pool. If you bind your process to fewer than the number of online CPUs it will not detect this and can create far too many threads.

Running with `PWQ_ACTIVE_CPU=<number of bound CPUs>` defined in your env can work around it, The fix in `libpwq` is to use `pthread_getaffinity_np()` to detect the number of CPUs the thread is bound to, rather than the number of online CPUs.

With either of the above I see both CPU utlization reach 85-90%:

![image](https://cloud.githubusercontent.com/assets/926840/17352048/b0df64aa-5901-11e6-9e48-37f46e4a26de.png)

and throughput improve by 20-60% with more than 1 CPU, however with 1 CPU we do get slightly slower with more clients:

![image](https://cloud.githubusercontent.com/assets/926840/17352059/c02f4542-5901-11e6-9499-6574b791d1d8.png)

**Comment by ianpartridge** [comment]
Great work - @frankeh can help us get fixes into `libpwq` 👍

**Comment by djones6** [comment]
I'm closing this, as CPU utilization on Linux for simple 'Hello World' has improved to around 98% with improvements within the last month or so.  The performance and utilization for the GCD implementation on Linux (not currently the default) is a separate investigation.
