### ISSUE TITLE
Build on Linux under instruction, but cannot find  libCHttpParser.so

### ISSUE THREAD

**Issue by frogcjn** [IBM-Swift/Kitura#429]
```bash
.build/debug/myFirstProject: error while loading shared libraries: libCHttpParser.so: cannot open shared object file: No such file or directory
```

**Comment by frogcjn** [comment]
```bash
cp libCHttpParser.so /usr/local/lib
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

temporarily solve the problem.

**Comment by shmuelk** [comment]
Actually just add -Xlinker -rpath -Xlinker .build/debug to your swift build command.

That is actually already in the master branch of SPM, it just didn't get into the 04/25 drop of Swift 3.0

**Comment by djones6** [comment]
I believe the linker option is fixed by this commit: https://github.com/apple/swift-package-manager/commit/2c89797c3881be85a48e60c98e6525aac9fb6dfd
This is included in the latest (05/03) snapshot,  although Kitura hasn't migrated to that snapshot yet ( #432 )
The option used in that commit is -rpath=$ORIGIN (literal - you'll need to escape the $) which at runtime expands to the directory containing the executable.  This has the advantage that the binaries can be moved / invoked from anywhere.

**Comment by dfirsht** [comment]
This does appear to have been solved in the 05/03 snapshot. Therefore we can probably get rid of `-Xlinker -rpath -Xlinker .build/debug` in the Makefile.

**Comment by dfirsht** [comment]
Closing based on migration to 05/03 snapshot.
