### ISSUE TITLE
Improve performance by batching writes to the socket

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#430]
Instead writing all sorts of things directly to the socket, write them to the socket through a buffer.

**Comment by djones6** [comment]
I just gave this a quick test on Linux:  the responses/sec I get increase from 20.9k to 30.4k - a nice 45% improvement!

Without buffering:
`numactl --physcpubind=0,1,2,3 --membind=0 /home/djones6/kitura/Kitura-TechEmpower/build-unbuffered/release/Kitura-TechEmpower`
`numactl --cpunodebind=1 --membind=1 wrk -t16 -c128 -d10s http://127.0.0.1:8080/plaintext`
`Running 10s test @ http://127.0.0.1:8080/plaintext`
`  16 threads and 128 connections`
`  Thread Stats   Avg      Stdev     Max   +/- Stdev`
`    Latency   122.82ms  637.02ms   6.41s    96.13%`
`    Req/Sec     1.90k     1.80k   13.75k    72.52%`
`  211182 requests in 10.10s, 23.16MB read`
`  Socket errors: connect 0, read 211182, write 0, timeout 0`
`Requests/sec:  20909.54`
`Transfer/sec:      2.29MB`

With buffering:
`numactl --physcpubind=0,1,2,3 --membind=0 /home/djones6/kitura/Kitura-TechEmpower/build-buffered/release/Kitura-TechEmpower`
`numactl --cpunodebind=1 --membind=1 wrk -t16 -c128 -d10s http://127.0.0.1:8080/plaintext`
`Running 10s test @ http://127.0.0.1:8080/plaintext`
`  16 threads and 128 connections`
`  Thread Stats   Avg      Stdev     Max   +/- Stdev`
`    Latency     9.40ms   59.37ms   1.60s    96.47%`
`    Req/Sec     2.40k     1.88k   12.58k    66.29%`
`  304489 requests in 10.01s, 33.39MB read`
`  Socket errors: connect 0, read 304483, write 0, timeout 0`
`Requests/sec:  30422.44`
`Transfer/sec:      3.34MB`

**Comment by shmuelk** [comment]
Were both tests using the same code base with the exception of the performance fix? Or were there other differences as well?

What is the CPU utilization like now?

**Comment by djones6** [comment]
My compare was done on the same codebase, with the exception of Kitura-net.  Buffered was built with 0.11.6, and I moved back to 0.11.5 for the baseline (unbuffered) build.

CPU utilization was similar - here is the corresponding CPU utilization information (over a 10 second period):
Unbuffered
`CPU time delta: user=14.780 sys=17.720 total=32.500`
`CPU 0: 84.3 %`
`CPU 1: 83.1 %`
`CPU 2: 74.6 %`
`CPU 3: 83.2 %`

Buffered
`CPU time delta: user=24.840 sys=8.660 total=33.500`
`CPU 0: 86.8 %`
`CPU 1: 86.4 %`
`CPU 2: 86.0 %`
`CPU 3: 79.4 %`

So utilization was a fraction higher in the buffered case,  but not significantly.  A significant proportion of the CPU used shifted from 'sys' to 'user'.

I would imagine that implementing keep-alive support will help achieve higher CPU utilization as well as throughput.  Since every request results in setting up and tearing down a TCP connection, I expect that this is a bottleneck with >1 CPU.
