### ISSUE TITLE
Asking for opinions about a higher level client request "library"

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#436]
There have been some requests for a higher level client request "library" for Kitura. These requests are largely in light of the bare bones functionality available today in KituraNet's ClientRequest/ClientResponse classes.

A few questions:

   1) What should this look like?
         a) Is RequestJs a good example to model?
   2) Should this be part of Kitura or a separate repo?

Any other comments would also be welcome.

**Comment by kweinmeister** [comment]
FYI @glennrfisher @AntonAleksandrov

**Comment by AntonAleksandrov** [comment]
At some point NSURLSession will be available, and we'll see multiple http client libraries coming from community. I believe we'll also hear from big players like Alamofire. 

That said, I do agree that there's nothing to solve this problem as of today and having a simple HttpClient abstraction would be very instrumental. To answer the above questions - as a node developer having request.js style API would make me really happy. However as an iOS developer my preference would be to see something similar to NSURLSession API. So we need to carefully think here what's the best direction. In any case - I think this should be a separate project that can be consumed on it's own regardless of whether you're using Kitura server or not. This way we'll be able to support both web server and worker models. 

In order to facilitate some of the BMS SDKs development due to the reasons outlines by @shmuelk above we've created a very simple abstraction on top of Kitura-Net (https://github.com/ibm-bluemix-mobile-services/bluemix-simple-http-client-swift). The plan was to throw it away once we have a better solution, but it can also be evolved to something bigger if required.

**Comment by michalkalinowski-** [comment]
+1 for _swifty_ API. Maybe even following basic Alamofire interface would not be too hard:

```
Alamofire.request(.GET, "https://httpbin.org/get", parameters: ["foo": "bar"])
     .response { request, response, data, error in
       ...
    }
    .responseData {...}
    .responseString {...}
    .responseJSON {...}
```

**Comment by michalkalinowski-** [comment]
Is anyone handling this? If not I can create a branch with proposal.

**Comment by ianpartridge** [comment]
Hi - I don't think anyone's got beyond the brainstorming stage.  Contributions are very welcome!

**Comment by glennrfisher** [comment]
I'm not sure if this matches the API that you would want to expose, but we've made some progress on a Watson SDK that uses KituraNet for networking.

As we did in our open-source Watson Developer Cloud iOS SDK, we created a helper class to abstract the construction of a REST request. (In the iOS SDK, this class implements Alamofire's `URLRequestConvertible` protocol.)

Here's a link to that helper class, which we've been calling [`RestRequest`](https://github.com/IBM-Swift/swift-watson-sdk/blob/master/Sources/RestKit/RestRequest.swift).

Here's a link to some code showing how we use that helper class to make a networking call and deserialize the results into either an object or error: [`InsightsForWeather`](https://github.com/IBM-Swift/swift-watson-sdk/blob/master/Sources/InsightsForWeather/InsightsForWeather.swift#L49)

We've experimented with lots of different architectures for networking in the iOS SDK: Alamofire, an abstraction upon Alamofire, Alamofire routers, AlamofireObjectMapper, and NSURLSession. In our experience, this pattern is far-and-away the best for our SDK--especially when used with Freddy for safe JSON serialization/deserialization.

**Comment by michalkalinowski-** [comment]
@glennrfisher I don't think swift-watson-sdk repo is public :(

**Comment by glennrfisher** [comment]
Yeah, our team decided to keep it private until it's more functional. Sorry if some of y'all can't see it.

Here's the same helper class in our iOS SDK: [`RestRequest`](https://github.com/watson-developer-cloud/ios-sdk/blob/rest-kit/Source/RestKit/RestRequest.swift)

And here's a link to some sample code using that class: [`LanguageTranslation`](https://github.com/watson-developer-cloud/ios-sdk/blob/rest-kit/Source/LanguageTranslationV2/LanguageTranslation.swift#L250)

Our plan right now is to continue work in the `swift-watson-sdk` repository. After we get to a stable state, though, we plan to consider separating out the `RestRequest` class if others would find it helpful.

**Comment by glennrfisher** [comment]
I think @michalkalinowski- has a great point about easing the transition to Alamofire, though. Although our team has found the `RestRequest` helper class useful, I suspect more people would want an Alamofire-like library first.

I think there would definitely be some value in making a simple framework using KituraNet that mimics the Alamofire API. Then when Alamofire adds support for Swift 3 and Swift on Linux, it would be simple for users to make that transition.

**Comment by dfirsht** [comment]
Overall I would say the feedback for creating this "library" is positive, although there is some differences in ideas how to implement. I went ahead and made an epic for the creation of this library and added it to the backlog. We will take these comments into consideration when we start designing it.
