### ISSUE TITLE
StaticFileServer does not serve files to browser

### ISSUE THREAD

**Issue by devgg** [IBM-Swift/Kitura#486]
I created a small webserver:

```
import Kitura
import KituraNet
import KituraSys


let router = Router()
let staticFileServer = StaticFileServer()

router.get("/*", middleware: staticFileServer);

let server = HTTPServer.listen(port: 80, delegate: router)
Server.run()
```

When I execute `wget url.com/css/style.css` the file gets loaded as expected.

When I call the website in the chrome the index.html is loaded but the css `(<link rel="stylesheet" href="css/style.css">)` fails to load.
The error I get is `Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://url.com/css/style.css/".`

I think the browser appends an `/` to the url. Which lets the StaticFileServer try to serve a directory.

**Comment by NikitaSullivan** [comment]
Hi devgg,

Thanks for raising this issue, someone will take a look at it shortly.

**Comment by irar2** [comment]
The problem  here is the *, if you change to 
router.get("/", middleware: staticFileServer)
the code should work. 
It happens because we remove the matched path from the requested path to get the file path, and for /* the whole requested path matches. 
We don't know the best way to solve this yet, but we will have a solution shortly.

**Comment by shmuelk** [comment]
Reviewed the code. Looks good.
