### ISSUE TITLE
Migration to 06-06 swift snapshot

### ISSUE THREAD

**Issue by NikitaSullivan** [IBM-Swift/Kitura#528]
- [x] LoggerAPI - (no changes)
- [x] SwiftyJSON - (no changes)
- [x] KituraSys - (no changes)
- [x] KituraNet - (no changes)
- [x] Kitura
- [x] HeliumLogger - (no changes)
- [x] KituraSample - (no changes)
- [x] CouchDB - (no changes)
- [x] Redis - (no changes)
- [x] KituraCredentials - (no changes)
- [x] Kitura-Credentials-Sample - (no changes)
- [x] KituraSession - (no changes)
- [x] GRMustache - (no changes)
- [x] Kitura-TemplateEngine - (no changes)
- [x] Kitura-MustacheTemplateEngine - (no changes)

**Comment by infinitezest** [comment]
Hi - I have tried to compile Kitura from Xcode 8 beta, which contains Swift 3.0 Preview 1 (snapshot from June 13, 2016). Following are some notes on the issues:

- There are issues with SwiftyJSON, Socket, and KituraSys. 
- Kitura and KituraNet are not compiling, but they probably would if dependencies compile.

Most of the issues seem pretty minor. Running Swift 3 Migrator seems to fix most of them in KituraSys. Migrator related fixes/changes are in these areas (lot of files are changed with simple changes):

- Grand Renaming in Foundation — NS prefix is dropped out of many Foundation classes (NSData to Data, NSCharacterSet to CharacterSet, NSTimeInterval to TimeInterval, etc.)

- Now argument label is required for the first parameter as well for functions in Swift (different from Obj-C behavior). Migrator goes and inserts _ for the missing first argument labels.

- Lower-casing enum cases; Plus: enums became more Swifty

- DispatchQueue class (instead of dispatch_queue_t), DispatchQueueAttributes enum, etc.
- Miscellaneous

xcodeproj generation, etc. are fine (added this to path: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin to get the preview 1 toolchain)

Thought this might help in planning, etc — probably this Xcode 8 stuff needs to be a separate ticket. Non-kitura repos will need to go through migration as well ...

- Ram.

**Comment by ianpartridge** [comment]
Thank you for investigating this.  We need to check the status of swift-corelibs-foundation too, as Kitura supports Linux as well.

**Comment by collinhundley** [comment]
It looks like Swift 3.0 Preview 1 includes some pretty significant changes - even after the auto-migration I had plenty of errors to fix.  It would be nice to develop in Xcode 8 for some of its new features, like the ability to switch toolchains without restarting Xcode.

As a side note: are any of you from IBM here at WWDC?  I'd love to meet up and chat if you are.

**Comment by ianpartridge** [comment]
Yes there are a few of the team there including @pbohrer @seabaylea and @rfdickerson . https://developer.apple.com/wwdc/schedule/#/details/415 is worth attending :)

**Comment by collinhundley** [comment]
I was wondering if you guys would be involved in that session :)  It would be great to see some sort of partnership between Apple and IBM on this.

Sorry to keep blowing up this thread, but is there a Slack channel or anything like that for Kitura?  It would be nice to have a place to ask questions, get feedback and collaborate.

**Comment by ianpartridge** [comment]
No Slack, but we do have a gitter - see https://gitter.im/IBM-Swift/Kitura

**Comment by dfirsht** [comment]
Validated by automatic testing.
