### ISSUE TITLE
Latency in framework?

### ISSUE THREAD

**Issue by proyb6** [IBM-Swift/Kitura#558]
Worse latency is 305ms although the avg latency is amazing, what was wrong with the example on the myFirstPoject tutorial on github?
```
test1-MacBook-Pro:khello yanli$ wrk -t2 -c500 --latency -d30 http://localhost:8090
Running 30s test @ http://localhost:8090
2 threads and 500 connections
Thread Stats Avg Stdev Max +/- Stdev
Latency 505.13us 5.04ms 305.45ms 99.93%
Req/Sec 2.27k 1.74k 5.32k 44.93%
Latency Distribution
50% 394.00us
75% 443.00us
90% 512.00us
99% 768.00us
16279 requests in 30.11s, 1.68MB read
Socket errors: connect 251, read 650, write 4, timeout 0
Requests/sec: 540.71
Transfer/sec: 57.03KB
```

In contrast, Vapor web framework or Go (pure router) could reach 420k+ req/s and >1million req/s respectively on Macbook Pro.

**Comment by ianpartridge** [comment]
Thank you. We're aware of this and will be doing work to improve worst-case outliers under #410

**Comment by proyb6** [comment]
Thanks!

**Comment by proyb6** [comment]
Need to clear some doubt on the latency in Kitura, is the "us" which is many times faster than "ms" was a successful request or a bug? As far as I test Go would achieve >9ms at 99-percentile. What is the trick to render in less than a millisecond?

**Comment by ianpartridge** [comment]
I'm sorry, I don't know.

**Comment by proyb6** [comment]
@ianpartridge Ok, would be ideal to serve static page with that timing, most languages do not optimize as best.

**Comment by wildfiremedia** [comment]
@ianpartridge I realize someone explain keepalive is not supported in Kitura?
http://stackoverflow.com/questions/38160261/kitura-slow-or-low-request-per-second

**Comment by ianpartridge** [comment]
Kitura `master` branch currently does not support Keepalive.  There is a `gcd_async` branch under active development which adds Keepalive support.

**Comment by djones6** [comment]
@proyb6 Re. your question on 'us' vs 'ms' in the wrk latency statistics:
ms = milliseconds, 1/1,000 of a second.
us (ascii equivalent of μs) = microseconds,  1/1,000,000 of a second.
1,000 μs = 1 ms.

FYI, there is a modified version of wrk called wrk2 - https://github.com/giltene/wrk2 - which produces a fixed load level rather than driving the server as fast as possible.  The latency statistics generated when a server is being driven at, say, 50% or 80% of capacity may be more relevant than when the server is flat-out.  I haven't experimented with it much but was planning my own experiments in this area.
