### ISSUE TITLE
Optimize the various "walker" classes

### ISSUE THREAD

**Issue by shmuelk** [IBM-Swift/Kitura#588]
Kitura has a pair of classes that are used to walk various lists. They do this with closures. The goal is to improve how this is done.

**Comment by djones6** [comment]
Performance numbers for Kitura 0.21, the async changes (issue #435) and the issue_588 branch:

In summary, the changes so far appear to be worth ~1%.  However, the cost of having 6 routes defined rather than just the matching route is around 15-20%.

Workload is a simple plaintext response.  There are 6 routes defined in my sample code, only one route matches the request ("/plaintext"), and is the first one defined.

Benchmark 1: matching route calls end() rather than next()
```
Implementation | Avg Throughput | Max Throughput | Avg CPU | Avg RSS (kb)
---------------|----------------|----------------|---------|--------------
       default |        37159.7 |       37953.08 |    83.2 |       843132
         async |        53968.0 |       54205.75 |    91.7 |       959214
     async+588 |        54486.1 |       55296.46 |    91.9 |       967772
```
Benchmark 2: matching route calls next()
```
Implementation | Avg Throughput | Max Throughput | Avg CPU | Avg RSS (kb)
---------------|----------------|----------------|---------|--------------
       default |        31177.5 |       31365.68 |    83.2 |       710477
         async |        42370.0 |       42674.02 |    90.1 |       758337
     async+588 |        42825.2 |       43318.73 |    90.2 |       764589
```

**Comment by dfirsht** [comment]
Merged here: https://github.com/IBM-Swift/Kitura/pull/603
