### ISSUE TITLE
Upgrade to newest http-parser

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#628]
The Node.js folks have released 2.7.1 which fixes a problem with Content-Length parsing. We should update the version we bundle with Kitura.

**Comment by rfdickerson** [comment]
Any discussions regarding getting rid of HttpParser as a C library dependency, or have we dropped that?

CHttpParser is responsible for the awkward XCode setup that involves adding the $SRCROOT/.build/debug to the Library Search paths for Kitura-Net and Kitura.

**Comment by ianpartridge** [comment]
@rfdickerson https://github.com/IBM-Swift/Kitura-net/issues/52

**Comment by shmuelk** [comment]
I think the ultimate fix is actually in SPM. SPM should see that there are C packages and add the build directory to the library search path for packages that depend on the C package.

**Comment by simplepanda** [comment]
I'm very much of the same mind as @shmuelk. There's a lot of existing C library code that probably doesn't/shouldn't need to be rewritten in Swift, at least from a "need the functionality" perspective.  The libraries already work, after all.

I think the key is the difference between library internals and library interface, though. It's a different story if you're trying to make an importable package that is "Swifty" so you can later re-use it in other applications.

For example, I'm regularly patching a MySQL client right now ([SimpleSQL](https://github.com/simplepanda/SimpleSQL.git)) that I'm already using in a bunch of production projects. 

It's not native Swift - it just provides a Swift interface to Connector/C. I wrote it because accessing the C library every time I want data from a database involves a lot of extra code with a lot of ```UnsafeMutablePointer``` use and a lot of data type detection and and a lot of iterating through field descriptors and a lot of casting / data conversion from ```char *``` pointers, all just to get basic data in and out of my RDBMS in my Swift server / command line apps.

When instead I can just do:

```swift
var record = getConnection()?
   .createQuery()?
   .executeQuery("select * from record where id = 1")?
   .rows
   .first

if (record != nil) {
   // here is my unique record. 
   // if i didn't get here, something i can't mitigate 
   // against happened so just handle it gracefully.
}
```

So I'm still getting 100% of the compatibility and performance of the underlying Connector/C library but I'm bridging that into Swift so I can rapidly develop new apps on top of it. Not rewriting the networking code, memory management, etc of Connector/C and dealing with the utter hash (see what I did there?) of MySQL's connection authentication mechanisms - I'm just crafting a shim to ease the way I interact with the library for day to day developing.

I see a lot of people hoping for native MySQL client libraries in pure Swift, but unless one comes from Oracle, I'm probably never touching one with a ten foot pole. :)

The only downside is that I have to make sure I at some point did an ```apt-get install libmysqlclient-dev``` on my deployment machine and add ```-Xcc -I/usr/local/include/mysql -Xlinker -L/usr/lib/x86_64-linux-gnu``` every time I build my app and of course you have to add appropriate library/header search paths in Xcode when developing.

Neither are a huge problem but both are things that SPM should evolve to deal with rather than doing all the work to re-write libraries in pure Swift just to avoid some build system setup and/or development tool configuration headaches.

I even have this pipe dream of SPM integrating with HomeBrew/MacPorts/apt to let modules specify their underlying library requirements, but I'm not holding my breath on that... :)

Don't get me wrong, the nerd in me loves seeing new code created, but the part of me that has to rapidly prototype, QA, and deploy apps into commercial production thinks evolving SPM is the way better solution. Leveraging C brings a lot of 'known quantity' to the party, on that front.

Just my $0.02.

(wow, that was verbose - sorry)

**Comment by dfirsht** [comment]
Merged in https://github.com/IBM-Swift/CHTTPParser/pull/6
