### ISSUE TITLE
Support a template engine

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#650]

**Comment by vadimeisenbergibm** [comment]
The status of GRMustache:
On OS X all the 313 tests pass.
On Linux, 284 of the 313 (90.7%) pass.

29 tests are disabled due to 5 defects. Distribution of disabled tests by defects:
https://bugs.swift.org/browse/SR-585 5 tests
https://bugs.swift.org/browse/SR-957 11 tests
https://bugs.swift.org/browse/SR-2483 1 test (suite of 28 tests counted as one test)
https://bugs.swift.org/browse/SR-2486 6 tests
https://bugs.swift.org/browse/SR-2477 6 tests

**Comment by vadimeisenbergibm** [comment]
Example of NSError issue in GRMustache - defect https://bugs.swift.org/browse/SR-585
There is a user's code that throws `NSError` (`didRender` function) and there is a user's code that catches the error (`catch let error as NSError`).

```swift
 func testDidRenderFunctionObservesRenderingNSError() {
        var failedRendering = false
        let didRender = { (tag: Tag, box: MustacheBox, string: String?) in
            failedRendering = (string == nil)
        }

        let template = try! Template(string: "-{{.}}-")
	template.baseContext = template.baseContext.extendedContext(by: Box(didRender))
        failedRendering = false
        do {
            let _ = try template.render(with: Box({ (info: RenderingInfo) -> Rendering in
		throw NSError(domain: "TagObserverError", code: 1, userInfo: nil)
            }))
            XCTAssert(false)
        } catch let error as NSError {
            XCTAssertEqual(error.domain, "TagObserverError")
            XCTAssertEqual(error.code, 1)
        }
        XCTAssertTrue(failedRendering)
    }
```

**Comment by vadimeisenbergibm** [comment]
Converting `NSError` to `Error` and throwing/catching as Error does not help either, the program crashes on catch:
```swift
func foo() throws {
    let error: Error = NSError(domain: "", code: 0, userInfo: nil)
    print("after assignment of NSError to error")
    throw error
}

do {
    try foo()
} catch {
    print("caught error \(error)")
}
```

**Comment by vadimeisenbergibm** [comment]
Throwing an `NSError`  and catching as `Error` does not help:
```swift
func foo() throws {
    let error = NSError(domain: "", code: 0, userInfo: nil)
    throw error
}

do {
    try foo()
} catch {
    print("caught error \(error)")
}
```

**Comment by vadimeisenbergibm** [comment]
The status of GRMustache:

**Swift 3.0 Release**
On OS X all the 313 tests pass.
On Linux, 284 of the 313 (90.7%) pass.

**DEVELOPMENT-SNAPSHOT-2016-09-19-a**
On OS X all the 313 tests pass.
On Linux, 290 of the 313 (92.6%) pass.

23 tests are disabled due to 4 defects. Distribution of disabled tests by defects:
https://bugs.swift.org/browse/SR-585 5 tests
https://bugs.swift.org/browse/SR-957 11 tests
https://bugs.swift.org/browse/SR-2483 1 test (suite of 28 tests counted as one test)  A PR exists https://github.com/apple/swift-corelibs-foundation/pull/647.
https://bugs.swift.org/browse/SR-2477 6 tests. A PR exists https://github.com/apple/swift-corelibs-foundation/pull/643.

**Comment by sgharms** [comment]
@vadimeisenbergibm Thank you for giving me this issue to track resolution.

**Comment by vadimeisenbergibm** [comment]
@sgharms You are welcome.

**Comment by ianpartridge** [comment]
Closing because we now support Stencil and GRMustache.

**Comment by vadimeisenbergibm** [comment]
The status of GRMustache:

Swift 3.0.1 Release
On OS X all the 313 tests pass.
On Linux, 296 of the 313 (95%) pass.

17 tests are disabled due to 3 defects. Distribution of disabled tests by defects:
https://bugs.swift.org/browse/SR-585 5 tests
https://bugs.swift.org/browse/SR-957 11 tests
https://bugs.swift.org/browse/SR-2483 1 test (suite of 28 tests counted as one test) A PR exists apple/swift-corelibs-foundation#647.

**Comment by vadimeisenbergibm** [comment]
The status of GRMustache:
Swift 3.1. All the tests pass on OS X and Linux.

The only remaining defect https://bugs.swift.org/browse/SR-957, a workaround provided in the code - https://github.com/IBM-Swift/SwiftRuntime/issues/27#issuecomment-292083222

**Comment by ludagoo** [comment]
There is still a not on [this](http://www.kitura.io/en/resources/tutorials/templating.html) page saying linux is not supported.

**Comment by vadimeisenbergibm** [comment]
@ludagoo I have submitted a PR - https://github.com/IBM-Swift/kitura.io/pull/48.

**Comment by joekiller** [comment]
The Swiftruntime#27 link is dead. I found another patch here: https://github.com/IBM-Swift-Sunset/GRMustache.swift/pull/7/commits/56ecaf22ce9fdfc6ad5d3ec0b2a37f64bf513464
