### ISSUE TITLE
SQL database abstraction layer

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Kitura#680]

**Comment by krugazor** [comment]
Not an abstraction layer, but I've been using a SQLite3 interface successfully (it's more or less in sync with Kitura's main branch for test purposes, although I use PREVIEW4 rather than the dated variant), maybe that could be a first step, or a stopgap on the road to epicness.

https://github.com/krugazor/swiftydb

Unfortunately, the lack of reflection capabilities in Swift 3 seriously hampers any attempt at column <-> property mapping, but hey... it works.
