### ISSUE TITLE
Credentials middleware should fail explicitly if session isn't available

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Kitura#690]
@youming-lin commented on [Mon Aug 15 2016](https://github.com/IBM-Swift/Kitura-Credentials/issues/15)

Currently, if session isn't configured and added to middlewares before credentials is used, authentication can fail silently (i.e., if web-based OAuth2 authentication, authentication callback can fail with a 404 Not Found error). We should explicitly throw(?) an error if session isn't available.

**Comment by youming-lin** [comment]
@ianpartridge What is the current plan for this item? As I understand, not all Credentials plugins require session; however, the web-based OAuth2 flows do.

**Comment by youming-lin** [comment]
@irar2 Do you have any preference on what should be done for this? One possibility is change [this block](https://github.com/IBM-Swift/Kitura-Credentials/blob/master/Sources/Credentials/Credentials.swift#L217-L231) to be able to redirect to the explicitly specified `successRedirect` URL without checking for session.

**Comment by irar2** [comment]
This block will never be reached in case there is no session, we will fail in handle().

We can add an error message (Log.error) to fail(). Something like: "The authentication failed either because the authentication data was not recognized by any non-redirecting plugin, or because there is no session available for the request required by redirecting authentication."

What do you think?

**Comment by youming-lin** [comment]
Not sure I understand. When I tested the Facebook web login without session, it hit the `onSuccess` callback, but since session wasn't available it went straight to `next()` and eventually Kitura returned a 404 because `response.send` was never called by the middleware.

Since Facebook web login does not require session in order to be used, I think we need to refactor code so that this path works correctly without session.

**Comment by irar2** [comment]
@youming-lin I finally understand the problem: you simply called Credentials.authenticate() without going through handle() first. This was not our intention, the scenario should be: request for protected path is checked in handle() and redirected if necessary to login page, and authenticate() called from there. All this with session, otherwise it makes no sense to log in if there is no state that remembers that the user is logged in.

So, the proposed solution is to add an error message as in my previous comment (and also add this to the response itself). And add a similar treatment in case  there is no session in authenticate(), i.e. set response.error to indicate that the server was not configured properly.

**Comment by youming-lin** [comment]
@irar2 I'm still not sure I'm understanding your points. Are you saying that session **is** required for web-based Facebook login? This is contrary to what I heard previously.

**Comment by irar2** [comment]
Yes, session is required for web-based login, otherwise what is the meaning of logging in? Session is not needed for token-based authentication.

I added missing session setup to the examples in CredentialsFacebook and Google README files.

**Comment by youming-lin** [comment]
@irar2 I see, it was my mistake. I forgot this line: `router.all("/private", middleware: credentials)` when I was testing it. Now I get `401 Unauthorized` when I disable session.

I'll go ahead with your suggestion of adding an extra `Log.error` in `fail()` with a more detailed error message.

**Comment by youming-lin** [comment]
@irar2 I added this `Log.error` in `handle()`. Would this work?

```swift
...
else {
                    Log.error("Authentication failure: there is no redirecting authentication plugin registered, or session is not configured.")
                    self.fail(response: response, status: passStatus, headers: passHeaders)
}
...
```

https://github.com/IBM-Swift/Kitura-Credentials/blob/master/Sources/Credentials/Credentials.swift#L115-L117
