### ISSUE TITLE
Could the ResourcePathHandler class be public ?

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [IBM-Swift/Kitura#795]
I need to deploy with my package some static file (ssl certificates in particular).

I would like to create a Certificates folder in my package and the getAbsolutePath() method could help me to resolve the correct path.

Thanks,
/Jacopo

**Comment by shmuelk** [comment]
What class do you want made public? I can't find the ResourcePathHandler class.

**Comment by JacopoMangiavacchi** [comment]
It's in StaticFileServer

StaticFileServer.ResourcePathHandler.getAbsolutePath is what I need to access

**Comment by shmuelk** [comment]
Ok. I just found it. That file was added recently and my XCode project didn't have it.

**Comment by vadimeisenbergibm** [comment]
@shmuelk I am OK with making the class public. Maybe we should put one level higher - extract the class out of `StaticFileServer`.  Please decide on this.

**Comment by ianpartridge** [comment]
This functionality should perhaps be provided by `Kitura-Configuration` - a new package designed to ease deployment and configuration of Kitura apps.

**Comment by ianpartridge** [comment]
Our current thinking is that this function should not be made public under `StaticFileServer`, because the functionality is not related to serving static files, per se.

We need a better solution for deploying Kitura along with assets like certificates, configuration files etc. We're starting to gather requirements for that and this issue will form part of that.

For now, I've opened https://github.com/IBM-Swift/Kitura/issues/809 for this requirement.
