### ISSUE TITLE
Short Router lifespan leads to empty responses from server

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Kitura#808]
I have twice independently hit a problem where the router I have passed into Kitura has not been kept alive (because Kitura ServerDelegate keeps a weak reference to it.) This feels like a gotcha. Is there a way that Kitura can keep the router live without causing a leak?

Here are the two examples:

1) I have a function that creates the router from my application. In my `main.swift`:

``` swift
Kitura.addHTTPServer(port: 8090, with: Application.router())
Kitura.start()
```

2) In tests I start Kitura in the `setUp()` function:

``` swift
    override func setUp() {
        super.setUp()

        HeliumLogger.use()
        let router = Application().router
        Kitura.addHTTPServer(onPort: 8080, with: router)
        Kitura.start()
        sleep(2)
    }
```

In both these cases the server will write a log message that the connection was made, then send an empty response (no HTTP headers, no body, giving little information what might be going wrong). The issue goes away when the reference to the router is moved to a longer-lived scope.

**Comment by wildfiremedia** [comment]
Use ```defer``` to ensure it will always close? This may be similar to Vapor for a reference to troubleshoot.

https://github.com/vapor/engine/commit/2e10bfe6a3cda8794ec06fb24cae19841399cbc6

**Comment by na-gupta** [comment]
I don't see why making the server delegate a strong reference instead of a weak reference would introduce a memory leak. The only scenario I can think of in which that would be an issue is if lots of different server instances are created and references to them are kept around after the server is stopped. That doesn't seem like a realistic scenario to me, and maybe we can  simply make it a strong ref?

@shmuelk Do you know why the server delegate was made a weak reference?
