### ISSUE TITLE
Clarifying SSL setup on Linux vs MacOS

### ISSUE THREAD

**Issue by yoiang** [IBM-Swift/Kitura#839]
Hey y'all, I have a question about setting up an SSL server.

I have everything working a-ok on MacOS, where the only option is to use a chain file. The odd thing is that while I was unable to get it working with a `.pem` file (perhaps because mine aren't passworded and the [code path seems to fail if a password isn't specified](https://github.com/IBM-Swift/BlueSSLService/blob/master/Sources/SSLService.swift#L742-L746)), I was able to get it working using `.pfx` files I converted from my authority assigned `.pem`s (from Let's Encrypt). 

When I switch to Linux, however, neither using this path with `.pfx` files or `.pems` nor using the Linux specific `SSLConfig.init`s (such as in the example found [here](https://github.com/IBM-Swift/Kitura/wiki/Enabling-SSL-in-Kitura) seem to work. The server silently does not report any failure with my keys, however any client that attempts to connect via TLS/HTTPS is sent back a HTTP response.

**Comment by krystiansliwa** [comment]
Hi @yoiang I have similar question, but regarding macOS. 
Why we can't use here configuration like on linux - with cert and key?

**Comment by gtaban** [comment]
Hi @yoiang 

The underlying library to enable SSL/TLS on Kitura is OpenSSL on Linux and Apple Secure Transport on macOS. This was done so that the framework integrates with native libraries and no additional packages need to be installed. However what this means is that there are slight differences in behavior depending on platform.
One of these differences is the certificate format. OpenSSL accepts many types of certificate format, including PEM, whilst Secure Transport is limited to PKCS#12 (.pfx). That is why you can only do .pfx on macOS. Note that you can do both self-signed and cert chain in both PEM or PFX format.

Your second question is not completely clear to me. **Can you give me a bit more info please?**

Feel free to have a look at my SSL example with all different types of certificate configurations here: https://github.com/gtaban/SSLExample

More details on blog:
https://developer.ibm.com/swift/2016/09/22/securing-kitura-part-1-enabling-ssltls-on-your-swift-server/

**Comment by yoiang** [comment]
Hey @gtaban , thanks for the response!
In your example using the non-self signed Cert Chain config is commented out. Does that path currently work?

I am trying to use valid Cert Chain files I'm authorized using an authority. On MacOS everything works ok (when I use `.pfx` files,  I was unable to get the `.pem`s the `.pfx` came from to work on MacOS). When I switch to Linux and I'm forced to use `.pem`s HTTPS no longer works, all responses from the server are in HTTP and there are no error messages explaining why this has happened.

Writing this out it seems like I am having trouble with `.pem`s on Mac and Linux then, where converting them to `.pfx` works. Why would the `.pem`s fail? Where in the code can I look to see why they aren't being used or why the code is (silently) switching to HTTP?

Let me know if I can provide any more information!

**Comment by gtaban** [comment]
Hi @yoiang, I used to have that sample working with a cert chain on linux, let me have a look and I'll get back to you.

**Comment by gtaban** [comment]
Hi @yoiang 

I had commented out that line for other reasons: I was testing out pushing app to Bluemix and only one server could use the port variable. So I couldn't have two servers. You should be able to use the second server fine if you uncomment. 

_However_, I did discover a bug in my code in the cert chain code (I was using the wrong init), so if you do a pull, you can see the updated code. Uncomment that server, try it out and let me know if you have problems with the server on port 8080.

**Comment by ianpartridge** [comment]
Closing as old issue. Reopen if help still needed!
