### ISSUE TITLE
After removing using started() method in Kitura tests, different tests fail randomly in code coverage

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM-Swift/Kitura#869]
usually 2 tests fail out of 47, each time different ones

**Comment by na-gupta** [comment]
This fails even with the started() method being used as it was. See [build logs](https://travis-ci.org/IBM-Swift/Kitura/builds) for IBM-Swift/Kitura/tree/issue_869.

I think these builds may be failing because the osx builds are running very slow and the 10 second wait for expectations may not be enough currently. I don't see any other reason why these are failing.
