### ISSUE TITLE
Report JIRA issue(s) against Apple regarding issue with dependencies and map modules

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#89]
<a href="https://github.ibm.com/ricardo-olivieri"><img src="https://avatars.github.ibm.com/u/1573?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ricardo-olivieri](https://github.ibm.com/ricardo-olivieri)**
_Thursday Feb 04, 2016 at 16:09 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/89_

----

Discuss with Samuel how many issues to open against Apple.

**Comment by dfirsht** [comment]
@vadimeisenbergibm Can we close this issue now? If not, can you explain why?

**Comment by vadimeisenbergibm** [comment]
@dfirsht Apple provided a fix, that does not work for me. I will recheck the issue and will reopen the defect if needed. Let's close the issue once the defects are resolved and verified.

**Comment by vadimeisenbergibm** [comment]
https://bugs.swift.org/browse/SR-662 fixed by Apple and verified. Now order of dependencies for linkage is handled correctly by swift build.

https://bugs.swift.org/browse/SR-690 fixed by Apple, still does not work for me. I added a comment about it on the Apple JIRA - https://bugs.swift.org/browse/SR-690?focusedCommentId=12345&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12345

**Comment by vadimeisenbergibm** [comment]
I verified the issue https://bugs.swift.org/browse/SR-690 as resolved, it is fixed in the current version of swift package manager (not in the binaries)

**Comment by vadimeisenbergibm** [comment]
The issues are resolved in the Apple binaries from 25th of February.
